import type { Design } from "@/lib/design";
import type {
  Block,
  BlockType,
  LinkAnim,
  LinkWidth,
} from "@/lib/blocks";

/**
 * Sablona = kompletny vzhlad na jeden klik: tema + dizajn + startovacie bloky.
 * Pouziva ju onboarding (novy user) aj editor (kedykolvek neskor).
 *
 * DOLEZITE: kazda sablona ma explicitne farby pozadia, textu aj buttonov.
 * Farebne pary su kontrolovane na WCAG kontrast; gradientne buttony maju
 * citatelny text na oboch koncovych farbach. Ziadna sablona sa nespolieha na
 * priehladny glass/soft styl, ktory by na casti pozadia mohol splynut.
 */
export type TemplateCategory =
  | "Minimal"
  | "Gradient"
  | "Bold"
  | "Warm"
  | "Creator"
  | "Luxury"
  | "Experimental";

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  "Minimal",
  "Gradient",
  "Bold",
  "Warm",
  "Creator",
  "Luxury",
  "Experimental",
];

export type Template = {
  key: string;
  label: string;
  tagline: string;
  category: TemplateCategory;
  /** Highlights newly added premium looks in the picker. */
  featured?: boolean;
  theme: string;
  design: Design;
  starter: {
    type: BlockType;
    title?: string;
    text?: string;
    /** Optional per-link grid and motion presets. */
    width?: LinkWidth;
    anim?: LinkAnim;
  }[];
};

const STARTER_LINKS: Template["starter"] = [
  { type: "link", title: "Instagram" },
  { type: "link", title: "Latest" },
  { type: "socials" },
];

const TEMPLATE_DEFINITIONS: Template[] = [
  /* ---------- Minimal ---------- */
  {
    key: "paper",
    label: "Paper",
    tagline: "Warm cream, black buttons, timeless",
    category: "Minimal",
    theme: "classic",
    design: {
      bg: "solid",
      bgColor: "#f4f1ea",
      textColor: "#1a1a1a",
      btnBg: "#1a1a1a",
      btnText: "#f4f1ea",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "sans",
      fontHeading: "serif",
    },
    starter: [
      { type: "link", title: "Portfolio" },
      { type: "link", title: "Contact" },
      { type: "socials" },
    ],
  },
  {
    key: "mono",
    label: "Mono",
    tagline: "Pure black on white, no distractions",
    category: "Minimal",
    theme: "mono",
    design: {
      bg: "solid",
      bgColor: "#ffffff",
      textColor: "#000000",
      btnBg: "#000000",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "square",
      font: "sans",
      fontHeading: "sans",
    },
    starter: [
      { type: "link", title: "Website" },
      { type: "link", title: "Email me" },
      { type: "socials" },
    ],
  },
  {
    key: "ivory",
    label: "Ivory",
    tagline: "Soft off-white, outlined buttons",
    category: "Minimal",
    theme: "classic",
    design: {
      bg: "solid",
      bgColor: "#f7f5f0",
      textColor: "#1c1b19",
      btnBg: "#1c1b19",
      btnText: "#1c1b19",
      btnStyle: "outline",
      btnShape: "pill",
      font: "serif",
      fontHeading: "classic",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "slate",
    label: "Slate",
    tagline: "Cool grey, crisp and modern",
    category: "Minimal",
    theme: "mono",
    design: {
      bg: "solid",
      bgColor: "#eceef1",
      textColor: "#1f2933",
      btnBg: "#1f2933",
      btnText: "#eceef1",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "grotesk",
      fontHeading: "grotesk",
    },
    starter: STARTER_LINKS,
  },

  /* ---------- Gradient ---------- */
  {
    key: "sunset",
    label: "Sunset",
    tagline: "Warm orange-to-pink, white buttons",
    category: "Gradient",
    theme: "classic",
    design: {
      bg: "gradient",
      bgColor: "#c2410c",
      bgColor2: "#be185d",
      textColor: "#ffffff",
      btnBg: "#ffffff",
      btnText: "#c2402a",
      btnStyle: "fill",
      btnShape: "pill",
      font: "grotesk",
      fontHeading: "display",
    },
    starter: [
      { type: "link", title: "New single" },
      { type: "link", title: "Tour dates" },
      { type: "socials" },
    ],
  },
  {
    key: "ocean",
    label: "Ocean",
    tagline: "Blue gradient, crisp white buttons",
    category: "Gradient",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#1e3a8a",
      bgColor2: "#0e7490",
      textColor: "#ffffff",
      btnBg: "#ffffff",
      btnText: "#1e3a8a",
      btnStyle: "fill",
      btnShape: "pill",
      font: "sans",
      fontHeading: "grotesk",
    },
    starter: [
      { type: "link", title: "Book a call" },
      { type: "link", title: "Services" },
      { type: "socials" },
    ],
  },
  {
    key: "aurora",
    label: "Aurora",
    tagline: "Teal to violet, crisp white buttons",
    category: "Gradient",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#0f766e",
      bgColor2: "#6d28d9",
      textColor: "#ffffff",
      btnBg: "#ffffff",
      btnText: "#5b21b6",
      btnStyle: "fill",
      btnShape: "pill",
      font: "grotesk",
      fontHeading: "grotesk",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#ffffff",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "peach",
    label: "Peach",
    tagline: "Sunny peach to coral, dark buttons",
    category: "Gradient",
    theme: "bloom",
    design: {
      bg: "gradient",
      bgColor: "#ffd3a5",
      bgColor2: "#fd6585",
      textColor: "#3a1f2b",
      btnBg: "#3a1f2b",
      btnText: "#ffe9d6",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "display",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "lavender",
    label: "Lavender",
    tagline: "Dreamy purple to pink",
    category: "Gradient",
    theme: "bloom",
    design: {
      bg: "gradient",
      bgColor: "#a18cd1",
      bgColor2: "#fbc2eb",
      textColor: "#2e2545",
      btnBg: "#2e2545",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "classic",
    },
    starter: STARTER_LINKS,
  },

  /* ---------- Bold ---------- */
  {
    key: "midnight",
    label: "Midnight",
    tagline: "Dark and sharp with bright buttons",
    category: "Bold",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#0e0e10",
      textColor: "#f4f4f5",
      btnBg: "#f4f4f5",
      btnText: "#0e0e10",
      btnStyle: "fill",
      btnShape: "pill",
      font: "grotesk",
      fontHeading: "grotesk",
    },
    starter: [
      { type: "link", title: "Latest drop" },
      { type: "link", title: "Shop" },
      { type: "socials" },
    ],
  },
  {
    key: "grape",
    label: "Grape",
    tagline: "Rich purple, playful, bold",
    category: "Bold",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#4c1d95",
      bgColor2: "#7c3aed",
      textColor: "#f5f3ff",
      btnBg: "#f5f3ff",
      btnText: "#4c1d95",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "grotesk",
      fontHeading: "grotesk",
    },
    starter: [
      { type: "link", title: "Watch now" },
      { type: "link", title: "Join Discord" },
      { type: "socials" },
    ],
  },
  {
    key: "electric",
    label: "Electric",
    tagline: "Black with neon-lime buttons",
    category: "Bold",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#0a0a0a",
      textColor: "#eaffb0",
      btnBg: "#d1ff3a",
      btnText: "#0a0a0a",
      btnStyle: "fill",
      btnShape: "square",
      font: "mono",
      fontHeading: "grotesk",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "cherry",
    label: "Cherry",
    tagline: "Deep wine with hot-red buttons",
    category: "Bold",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#1a0a0e",
      textColor: "#ffe1e7",
      btnBg: "#c91f47",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "pill",
      font: "grotesk",
      fontHeading: "grotesk",
    },
    starter: STARTER_LINKS,
  },

  /* ---------- Warm ---------- */
  {
    key: "sand",
    label: "Sand",
    tagline: "Editorial serif on warm sand",
    category: "Warm",
    theme: "sand",
    design: {
      bg: "gradient",
      bgColor: "#f3ece1",
      bgColor2: "#e3d7c3",
      textColor: "#3d3226",
      btnBg: "#3d3226",
      btnText: "#f3ece1",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "serif",
      fontHeading: "classic",
    },
    starter: [
      { type: "headline", text: "Work" },
      { type: "link", title: "Portfolio" },
      { type: "link", title: "Book me" },
    ],
  },
  {
    key: "forest",
    label: "Forest",
    tagline: "Deep green, calm, cream buttons",
    category: "Warm",
    theme: "sand",
    design: {
      bg: "solid",
      bgColor: "#1e3a2f",
      textColor: "#eef3ee",
      btnBg: "#eef3ee",
      btnText: "#1e3a2f",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "serif",
      fontHeading: "serif",
    },
    starter: [
      { type: "link", title: "Shop" },
      { type: "text", text: "Handmade, small batch." },
      { type: "socials" },
    ],
  },
  {
    key: "terracotta",
    label: "Terracotta",
    tagline: "Earthy clay with cream buttons",
    category: "Warm",
    theme: "sand",
    design: {
      bg: "solid",
      bgColor: "#a9472d",
      textColor: "#fff3ec",
      btnBg: "#fff3ec",
      btnText: "#a2432a",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "serif",
      fontHeading: "classic",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "latte",
    label: "Latte",
    tagline: "Creamy beige, coffee-brown buttons",
    category: "Warm",
    theme: "sand",
    design: {
      bg: "solid",
      bgColor: "#efe7db",
      textColor: "#4b3826",
      btnBg: "#6f4e37",
      btnText: "#efe7db",
      btnStyle: "fill",
      btnShape: "pill",
      font: "serif",
      fontHeading: "serif",
    },
    starter: STARTER_LINKS,
  },

  /* ---------- Creator ---------- */
  {
    key: "blush",
    label: "Blush",
    tagline: "Soft pink, elegant, adult-friendly",
    category: "Creator",
    theme: "bloom",
    design: {
      bg: "gradient",
      bgColor: "#fde8ef",
      bgColor2: "#e9d5f2",
      textColor: "#2f2336",
      btnBg: "#2f2336",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "display",
    },
    starter: [
      { type: "link", title: "Exclusive content" },
      { type: "link", title: "Instagram" },
      { type: "socials" },
    ],
  },
  {
    key: "rosegold",
    label: "Rose gold",
    tagline: "Soft warm neutral, dark buttons",
    category: "Creator",
    theme: "bloom",
    design: {
      bg: "gradient",
      bgColor: "#f7e7de",
      bgColor2: "#f0d5c8",
      textColor: "#4a2c2a",
      btnBg: "#4a2c2a",
      btnText: "#f7e7de",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "classic",
    },
    starter: [
      { type: "link", title: "Bookings" },
      { type: "link", title: "Price list" },
      { type: "socials" },
    ],
  },
  {
    key: "velvet",
    label: "Velvet",
    tagline: "Plum night with warm-gold buttons",
    category: "Creator",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#2b1024",
      bgColor2: "#4a1d3f",
      textColor: "#f6e7d8",
      btnBg: "#e8c9a0",
      btnText: "#2b1024",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "classic",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#e8c9a0",
    },
    starter: [
      { type: "link", title: "Exclusive content" },
      { type: "link", title: "Tip me" },
      { type: "socials" },
    ],
  },
  {
    key: "noirrose",
    label: "Noir rose",
    tagline: "Black and rose, sultry and clean",
    category: "Creator",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#0e0e10",
      textColor: "#ffd9e2",
      btnBg: "#be345c",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "display",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#be345c",
    },
    starter: [
      { type: "link", title: "Exclusive content" },
      { type: "link", title: "Instagram" },
      { type: "socials" },
    ],
  },

  /* ---------- New premium templates ---------- */
  {
    key: "onyx",
    label: "Onyx",
    tagline: "Near-black, sharp square avatar, mono",
    category: "Minimal",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#111113",
      textColor: "#ededed",
      btnBg: "#ededed",
      btnText: "#111113",
      btnStyle: "fill",
      btnShape: "square",
      font: "mono",
      fontHeading: "grotesk",
      avatarShape: "square",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#ededed",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "porcelain",
    label: "Porcelain",
    tagline: "Pure white, editorial serif, thin ring",
    category: "Minimal",
    theme: "classic",
    design: {
      bg: "solid",
      bgColor: "#ffffff",
      textColor: "#141414",
      btnBg: "#141414",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "serif",
      fontHeading: "classic",
      avatarShape: "circle",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#141414",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "marble",
    label: "Marble",
    tagline: "Soft grey, rounded photo, calm",
    category: "Minimal",
    theme: "mono",
    design: {
      bg: "gradient",
      bgColor: "#f2f3f5",
      bgColor2: "#e2e5ea",
      textColor: "#26292e",
      btnBg: "#26292e",
      btnText: "#f2f3f5",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "grotesk",
      fontHeading: "serif",
      avatarShape: "rounded",
      avatarRing: true,
      avatarRingColor: "#ffffff",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "mint",
    label: "Mint",
    tagline: "Fresh mint, deep-green buttons",
    category: "Gradient",
    theme: "sand",
    design: {
      bg: "gradient",
      bgColor: "#d6f5e3",
      bgColor2: "#a7e8c8",
      textColor: "#123a2a",
      btnBg: "#123a2a",
      btnText: "#e7fff2",
      btnStyle: "fill",
      btnShape: "pill",
      font: "grotesk",
      fontHeading: "grotesk",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#ffffff",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "coastal",
    label: "Coastal",
    tagline: "Sky blue to sand, breezy and light",
    category: "Gradient",
    theme: "classic",
    design: {
      bg: "gradient",
      bgColor: "#8ec5e8",
      bgColor2: "#f6e7c1",
      textColor: "#1d3b4d",
      btnBg: "#1d3b4d",
      btnText: "#f3f8fb",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "sans",
      fontHeading: "display",
      avatarShape: "circle",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#ffffff",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "dusk",
    label: "Dusk",
    tagline: "Indigo to magenta, glowing ring",
    category: "Gradient",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#312e81",
      bgColor2: "#be185d",
      textColor: "#fdf2ff",
      btnBg: "#fdf2ff",
      btnText: "#5b1d52",
      btnStyle: "fill",
      btnShape: "pill",
      font: "grotesk",
      fontHeading: "display",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#f9a8d4",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "citrus",
    label: "Citrus",
    tagline: "White with punchy orange buttons",
    category: "Bold",
    theme: "classic",
    design: {
      bg: "solid",
      bgColor: "#fffaf3",
      textColor: "#1a1207",
      btnBg: "#c2410c",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "grotesk",
      fontHeading: "grotesk",
      avatarShape: "rounded",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#c2410c",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "cyberlime",
    label: "Cyber lime",
    tagline: "Black with cyan-lime edge, techy",
    category: "Bold",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#08120f",
      textColor: "#c8fff0",
      btnBg: "#00e5c0",
      btnText: "#062a24",
      btnStyle: "fill",
      btnShape: "square",
      font: "mono",
      fontHeading: "grotesk",
      avatarShape: "square",
      avatarRing: true,
      avatarRingColor: "#00e5c0",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "steel",
    label: "Steel",
    tagline: "Cool graphite gradient, bright buttons",
    category: "Bold",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#1f2937",
      bgColor2: "#0b1220",
      textColor: "#e5edf7",
      btnBg: "#e5edf7",
      btnText: "#111827",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "grotesk",
      fontHeading: "grotesk",
      avatarShape: "rounded",
      avatarRing: true,
      avatarRingColor: "#e5edf7",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "sage",
    label: "Sage",
    tagline: "Muted sage green, cream buttons",
    category: "Warm",
    theme: "sand",
    design: {
      bg: "solid",
      bgColor: "#9aa886",
      textColor: "#20261a",
      btnBg: "#f6f4ea",
      btnText: "#38402c",
      btnStyle: "fill",
      btnShape: "rounded",
      font: "serif",
      fontHeading: "classic",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#f6f4ea",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "cocoa",
    label: "Cocoa",
    tagline: "Rich chocolate with tan buttons",
    category: "Warm",
    theme: "sand",
    design: {
      bg: "gradient",
      bgColor: "#3a271c",
      bgColor2: "#2a1a12",
      textColor: "#f3e3d3",
      btnBg: "#dcb892",
      btnText: "#2a1a12",
      btnStyle: "fill",
      btnShape: "pill",
      font: "serif",
      fontHeading: "serif",
      avatarShape: "circle",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#dcb892",
    },
    starter: STARTER_LINKS,
  },
  {
    key: "champagne",
    label: "Champagne",
    tagline: "Warm gold glow, elegant and premium",
    category: "Creator",
    theme: "bloom",
    design: {
      bg: "gradient",
      bgColor: "#f7ecd2",
      bgColor2: "#e7c58f",
      textColor: "#4a3617",
      btnBg: "#3d2c12",
      btnText: "#f7ecd2",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "classic",
      avatarShape: "circle",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#ffffff",
    },
    starter: [
      { type: "link", title: "Bookings" },
      { type: "link", title: "Exclusive content" },
      { type: "socials" },
    ],
  },
  {
    key: "orchid",
    label: "Orchid",
    tagline: "Deep purple night with pink buttons",
    category: "Creator",
    theme: "noir",
    design: {
      bg: "gradient",
      bgColor: "#2a0f3a",
      bgColor2: "#5b1d6e",
      textColor: "#f9e3ff",
      btnBg: "#ff5fa2",
      btnText: "#2a0f18",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "display",
      avatarShape: "circle",
      avatarRing: true,
      avatarRingColor: "#ff5fa2",
    },
    starter: [
      { type: "link", title: "Exclusive content" },
      { type: "link", title: "Tip me" },
      { type: "socials" },
    ],
  },
  {
    key: "ruby",
    label: "Ruby",
    tagline: "Black velvet with ruby and gold",
    category: "Creator",
    theme: "noir",
    design: {
      bg: "solid",
      bgColor: "#120608",
      textColor: "#ffe0e6",
      btnBg: "#c81d47",
      btnText: "#fff2f5",
      btnStyle: "fill",
      btnShape: "pill",
      font: "display",
      fontHeading: "classic",
      avatarShape: "circle",
      avatarSize: "lg",
      avatarRing: true,
      avatarRingColor: "#e8b84b",
    },
    starter: [
      { type: "link", title: "Exclusive content" },
      { type: "link", title: "Instagram" },
      { type: "socials" },
    ],
  },

  /* ---------- Luxury collection ---------- */
  {
    key: "maison",
    label: "Maison",
    tagline: "Champagne gold, couture typography",
    category: "Luxury",
    featured: true,
    theme: "midnight",
    design: {
      bg: "solid",
      bgColor: "#161513",
      textColor: "#f5ead7",
      btnBg: "#d7b46a",
      btnText: "#211a10",
      btnStyle: "fill",
      btnShape: "rounded",
      btnShadow: "subtle",
      btnBorder: "thin",
      btnSpacing: "relaxed",
      btnWeight: "medium",
      font: "manrope",
      fontHeading: "cormorant",
      avatarShape: "rounded",
      avatarAspect: "portrait",
      avatarSize: "xl",
      avatarFrame: "double",
      avatarRingColor: "#d7b46a",
      avatarPosition: "top",
    },
    starter: [
      { type: "headline", text: "The collection" },
      { type: "link", title: "Private appointments", width: "half" },
      { type: "link", title: "Lookbook", width: "half" },
      { type: "socials" },
    ],
  },
  {
    key: "emerald-suite",
    label: "Emerald suite",
    tagline: "Deep green, ivory and quiet luxury",
    category: "Luxury",
    featured: true,
    theme: "clay",
    design: {
      bg: "gradient",
      bgColor: "#0b2f26",
      bgColor2: "#123f34",
      textColor: "#f4ead7",
      btnBg: "#f4ead7",
      btnText: "#123f34",
      btnStyle: "fill",
      btnShape: "soft",
      btnShadow: "subtle",
      btnSpacing: "relaxed",
      font: "lora",
      fontHeading: "cormorant",
      avatarShape: "organic",
      avatarAspect: "portrait",
      avatarSize: "lg",
      avatarFrame: "line",
      avatarRingColor: "#d8bd7b",
      avatarPosition: "top",
    },
    starter: [
      { type: "link", title: "Signature collection" },
      { type: "link", title: "Book a consultation" },
      { type: "socials" },
    ],
  },
  {
    key: "silk",
    label: "Silk",
    tagline: "Powder blush with editorial depth",
    category: "Luxury",
    featured: true,
    theme: "lavender",
    design: {
      bg: "gradient",
      bgColor: "#f8e9e4",
      bgColor2: "#e8c7c1",
      textColor: "#3f252b",
      btnBg: "#3f252b",
      btnText: "#fff5f1",
      btnStyle: "fill",
      btnShape: "pill",
      btnShadow: "subtle",
      btnSpacing: "relaxed",
      font: "lora",
      fontHeading: "cormorant",
      avatarShape: "rounded",
      avatarAspect: "landscape",
      avatarSize: "lg",
      avatarFrame: "line",
      avatarRingColor: "#fff5f1",
    },
    starter: [
      { type: "link", title: "My journal" },
      { type: "link", title: "Selected work" },
      { type: "socials" },
    ],
  },
  {
    key: "obsidian-gold",
    label: "Obsidian gold",
    tagline: "Black glass, warm gold, gallery feel",
    category: "Luxury",
    featured: true,
    theme: "midnight",
    design: {
      bg: "gradient",
      bgColor: "#070707",
      bgColor2: "#211b12",
      textColor: "#fff4dc",
      btnBg: "#e5c27a",
      btnText: "#1b1408",
      btnStyle: "fill",
      btnShape: "square",
      btnShadow: "floating",
      btnBorder: "thin",
      btnSpacing: "normal",
      btnWeight: "bold",
      font: "montserrat",
      fontHeading: "cormorant",
      avatarShape: "square",
      avatarAspect: "wide",
      avatarSize: "lg",
      avatarFrame: "double",
      avatarRingColor: "#e5c27a",
    },
    starter: [
      { type: "headline", text: "Featured" },
      { type: "link", title: "View the collection" },
      { type: "link", title: "Private access" },
    ],
  },

  /* ---------- Experimental collection ---------- */
  {
    key: "prism",
    label: "Prism",
    tagline: "Night violet with luminous gradients",
    category: "Experimental",
    featured: true,
    theme: "aurora",
    design: {
      bg: "gradient",
      bgColor: "#111827",
      bgColor2: "#3b0764",
      textColor: "#ffffff",
      btnBg: "#fef08a",
      btnText: "#12231f",
      btnGradientColor: "#fef08a",
      btnGradientColor2: "#5eead4",
      btnStyle: "gradient",
      btnShape: "soft",
      btnShadow: "floating",
      btnSpacing: "relaxed",
      btnWeight: "bold",
      font: "manrope",
      fontHeading: "syne",
      avatarShape: "organic",
      avatarAspect: "square",
      avatarSize: "lg",
      avatarFrame: "glow",
      avatarRingColor: "#5eead4",
    },
    starter: [
      { type: "link", title: "Enter the studio", width: "half" },
      { type: "link", title: "Latest experiment", width: "half" },
      { type: "socials" },
    ],
  },
  {
    key: "brutalist",
    label: "Brutalist",
    tagline: "Raw type, hard shadows, zero fluff",
    category: "Experimental",
    featured: true,
    theme: "mono",
    design: {
      bg: "solid",
      bgColor: "#f5f0df",
      textColor: "#0b0b0b",
      btnBg: "#0b0b0b",
      btnText: "#f5f0df",
      btnStyle: "fill",
      btnShape: "square",
      btnShadow: "hard",
      btnBorder: "bold",
      btnSpacing: "compact",
      btnWeight: "bold",
      font: "mono",
      fontHeading: "syne",
      avatarShape: "square",
      avatarAspect: "portrait",
      avatarSize: "xl",
      avatarFrame: "line",
      avatarRingColor: "#0b0b0b",
      avatarPosition: "top",
    },
    starter: [
      { type: "headline", text: "Selected links" },
      { type: "link", title: "WORK_01", width: "half" },
      { type: "link", title: "CONTACT_02", width: "half" },
    ],
  },
  {
    key: "cobalt-pop",
    label: "Cobalt pop",
    tagline: "Electric blue with yellow punch",
    category: "Experimental",
    featured: true,
    theme: "ocean",
    design: {
      bg: "gradient",
      bgColor: "#173ea5",
      bgColor2: "#0b1e4f",
      textColor: "#ffffff",
      btnBg: "#f8d948",
      btnText: "#16120a",
      btnStyle: "fill",
      btnShape: "soft",
      btnShadow: "hard",
      btnBorder: "bold",
      btnSpacing: "normal",
      btnWeight: "bold",
      font: "manrope",
      fontHeading: "syne",
      avatarShape: "rounded",
      avatarAspect: "wide",
      avatarSize: "lg",
      avatarFrame: "line",
      avatarRingColor: "#f8d948",
    },
    starter: [
      { type: "link", title: "New release", width: "half" },
      { type: "link", title: "Join the list", width: "half" },
      { type: "socials" },
    ],
  },
  {
    key: "chrome",
    label: "Chrome",
    tagline: "Cool silver, ink black, design studio",
    category: "Experimental",
    featured: true,
    theme: "mono",
    design: {
      bg: "gradient",
      bgColor: "#f8fafc",
      bgColor2: "#cbd5e1",
      textColor: "#0f172a",
      btnBg: "#0f172a",
      btnText: "#f8fafc",
      btnStyle: "fill",
      btnShape: "rounded",
      btnShadow: "hard",
      btnBorder: "bold",
      btnSpacing: "compact",
      btnWeight: "bold",
      font: "raleway",
      fontHeading: "syne",
      avatarShape: "rounded",
      avatarAspect: "wide",
      avatarSize: "xl",
      avatarFrame: "double",
      avatarRingColor: "#0f172a",
    },
    starter: [
      { type: "link", title: "Selected projects", width: "half" },
      { type: "link", title: "Work with me", width: "half" },
      { type: "socials" },
    ],
  },

  /* ---------- New creator looks ---------- */
  {
    key: "afterglow",
    label: "Afterglow",
    tagline: "Plum night with vivid gradient buttons",
    category: "Creator",
    featured: true,
    theme: "aurora",
    design: {
      bg: "gradient",
      bgColor: "#3b0a39",
      bgColor2: "#7e174f",
      textColor: "#fff1f8",
      btnBg: "#be185d",
      btnText: "#ffffff",
      btnGradientColor: "#be185d",
      btnGradientColor2: "#7e22ce",
      btnStyle: "gradient",
      btnShape: "pill",
      btnShadow: "floating",
      btnSpacing: "relaxed",
      btnWeight: "bold",
      font: "manrope",
      fontHeading: "syne",
      avatarShape: "organic",
      avatarAspect: "portrait",
      avatarSize: "xl",
      avatarFrame: "glow",
      avatarRingColor: "#f472b6",
      avatarPosition: "top",
    },
    starter: [
      { type: "link", title: "Exclusive access", width: "half" },
      { type: "link", title: "Tonight's drop", width: "half" },
      { type: "socials" },
    ],
  },
  {
    key: "cloud-nine",
    label: "Cloud nine",
    tagline: "Airy pastel with deep violet contrast",
    category: "Creator",
    featured: true,
    theme: "lavender",
    design: {
      bg: "gradient",
      bgColor: "#eef2ff",
      bgColor2: "#fce7f3",
      textColor: "#312e81",
      btnBg: "#312e81",
      btnText: "#ffffff",
      btnStyle: "fill",
      btnShape: "pill",
      btnShadow: "subtle",
      btnSpacing: "relaxed",
      btnWeight: "medium",
      font: "raleway",
      fontHeading: "cormorant",
      avatarShape: "rounded",
      avatarAspect: "landscape",
      avatarSize: "xl",
      avatarFrame: "glow",
      avatarRingColor: "#ffffff",
    },
    starter: [
      { type: "link", title: "My favourites", width: "half" },
      { type: "link", title: "Latest update", width: "half" },
      { type: "socials" },
    ],
  },
];

/**
 * Every template gets a category-specific finish so the full legacy collection
 * benefits from the new Pro/Business controls without duplicating boilerplate.
 * A template can still override any value for a deliberately distinctive look.
 */
const CATEGORY_POLISH: Record<TemplateCategory, Partial<Design>> = {
  Minimal: {
    btnShadow: "none",
    btnBorder: "thin",
    btnSpacing: "normal",
    btnWeight: "medium",
    avatarFrame: "line",
    avatarFit: "cover",
    avatarPosition: "top",
  },
  Gradient: {
    btnShadow: "floating",
    btnBorder: "none",
    btnSpacing: "normal",
    btnWeight: "bold",
    avatarFrame: "glow",
    avatarFit: "cover",
    avatarPosition: "top",
  },
  Bold: {
    btnShadow: "floating",
    btnBorder: "none",
    btnSpacing: "compact",
    btnWeight: "bold",
    avatarFrame: "line",
    avatarFit: "cover",
    avatarPosition: "top",
  },
  Warm: {
    btnShadow: "subtle",
    btnBorder: "none",
    btnSpacing: "relaxed",
    btnWeight: "medium",
    avatarFrame: "shadow",
    avatarFit: "cover",
    avatarPosition: "top",
  },
  Creator: {
    btnShadow: "floating",
    btnBorder: "none",
    btnSpacing: "normal",
    btnWeight: "bold",
    avatarFrame: "glow",
    avatarFit: "cover",
    avatarPosition: "top",
  },
  Luxury: {
    btnShadow: "subtle",
    btnBorder: "thin",
    btnSpacing: "relaxed",
    btnWeight: "medium",
    avatarFrame: "double",
    avatarFit: "cover",
    avatarPosition: "top",
  },
  Experimental: {
    btnShadow: "hard",
    btnBorder: "bold",
    btnSpacing: "compact",
    btnWeight: "bold",
    avatarFrame: "line",
    avatarFit: "cover",
    avatarPosition: "top",
  },
};

export const TEMPLATES: Template[] = TEMPLATE_DEFINITIONS.map((template) => ({
  ...template,
  design: {
    ...CATEGORY_POLISH[template.category],
    ...template.design,
  },
}));

export function templateByKey(key: string | null | undefined): Template | null {
  return TEMPLATES.find((t) => t.key === key) ?? null;
}

/** Prevedie starter na plnohodnotne bloky s ID a poradim. */
export function templateBlocks(t: Template): Block[] {
  return t.starter.map((s, i) => {
    const base = { id: crypto.randomUUID(), position: i, is_active: true };
    if (s.type === "link")
      return {
        ...base,
        type: "link" as const,
        config: {
          title: s.title ?? "Link",
          url: "",
          featured: i === 0,
          width: s.width ?? "full",
          anim: s.anim ?? "none",
        },
      };
    if (s.type === "headline")
      return { ...base, type: "headline" as const, config: { text: s.text ?? "Section" } };
    if (s.type === "text")
      return { ...base, type: "text" as const, config: { text: s.text ?? "" } };
    if (s.type === "socials")
      return { ...base, type: "socials" as const, config: { items: [{ platform: "instagram" as const, url: "" }] } };
    return { ...base, type: "link" as const, config: { title: s.title ?? "Link", url: "" } };
  });
}
